In [1]:
import pandas as pd

data = {
    "Patient_ID": [101,102,103,104,105,106,107,108,109,110],
    "Age": [25,45,35,60,50,28,65,40,55,30],
    "Gender": ["Male","Female","Male","Female","Male",
               "Female","Male","Female","Male","Female"],
    "Department": ["Cardiology","Neurology","Cardiology","Orthopedic",
                   "Neurology","Cardiology","Orthopedic","Neurology",
                   "Cardiology","Orthopedic"],
    "City": ["Nagpur","Pune","Nagpur","Mumbai","Pune",
             "Nagpur","Mumbai","Pune","Nagpur","Mumbai"],
    "Treatment_Cost": [50000,35000,60000,45000,30000,
                       55000,70000,40000,65000,50000],
    "Hospital_Stay": [5,3,6,4,2,5,7,3,6,4]
}

df = pd.DataFrame(data)

df

   Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0         101   25    Male  Cardiology  Nagpur           50000              5
1         102   45  Female   Neurology    Pune           35000              3
2         103   35    Male  Cardiology  Nagpur           60000              6
3         104   60  Female  Orthopedic  Mumbai           45000              4
4         105   50    Male   Neurology    Pune           30000              2
5         106   28  Female  Cardiology  Nagpur           55000              5
6         107   65    Male  Orthopedic  Mumbai           70000              7
7         108   40  Female   Neurology    Pune           40000              3
8         109   55    Male  Cardiology  Nagpur           65000              6
9         110   30  Female  Orthopedic  Mumbai           50000              4

STANDARD FUNCTION

In [2]:
df['Age']

0    25
1    45
2    35
3    60
4    50
5    28
6    65
7    40
8    55
9    30
Name: Age, dtype: int64

In [3]:
df['Age'].std()  # how much data is spread

13.984515246037907

In [6]:
df['Age'].mean()  # average

np.float64(43.3)

In [7]:
# patient ke treatment cost kitni spread hai (use std ())
df['Treatment_Cost'].std()

12909.944487358056

In [8]:
df['Treatment_Cost'].mean()  # average

np.float64(50000.0)

In [9]:
# patients hospital me almost same no of days reh ya stay days me difference hai
df['Hospital_Stay'].std()

1.5811388300841898

In [10]:
df['Hospital_Stay'].mean()

np.float64(4.5)

In [15]:
# cardiology departement me kitna variation hai
df[df['Department']=="Cardiology"]["Age"].std()

13.5

FILL NA AND DROP NA

In [16]:
import pandas as pd

data = {
    "Patient_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    "Age": [25, 45, None, 60, 50, 28, 65, None, 55, 30],

    "Gender": [
        "Male", "Female", "Male", "Female", None,
        "Female", "Male", "Female", "Male", "Female"
    ],

    "Department": [
        "Cardiology", "Neurology", "Cardiology", "Orthopedic",
        "Neurology", "Cardiology", "Orthopedic", "Neurology",
        "Cardiology", "Orthopedic"
    ],

    "City": [
        "Nagpur", "Pune", "Nagpur", None,
        "Pune", "Nagpur", "Mumbai", "Pune",
        "Nagpur", "Mumbai"
    ],

    "Treatment_Cost": [
        50000, 35000, None, 45000, 30000,
        55000, 70000, 40000, None, 50000
    ],

    "Hospital_Stay": [
        5, 3, 6, None, 2,
        5, 7, 3, 6, 4
    ]
}

df = pd.DataFrame(data)

df

   Patient_ID   Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0         101  25.0    Male  Cardiology  Nagpur         50000.0            5.0
1         102  45.0  Female   Neurology    Pune         35000.0            3.0
2         103   NaN    Male  Cardiology  Nagpur             NaN            6.0
3         104  60.0  Female  Orthopedic    None         45000.0            NaN
4         105  50.0    None   Neurology    Pune         30000.0            2.0
5         106  28.0  Female  Cardiology  Nagpur         55000.0            5.0
6         107  65.0    Male  Orthopedic  Mumbai         70000.0            7.0
7         108   NaN  Female   Neurology    Pune         40000.0            3.0
8         109  55.0    Male  Cardiology  Nagpur             NaN            6.0
9         110  30.0  Female  Orthopedic  Mumbai         50000.0            4.0

In [17]:
df.isnull()

   Patient_ID    Age  Gender  Department   City  Treatment_Cost  Hospital_Stay
0       False  False   False       False  False           False          False
1       False  False   False       False  False           False          False
2       False   True   False       False  False            True          False
3       False  False   False       False   True           False           True
4       False  False    True       False  False           False          False
5       False  False   False       False  False           False          False
6       False  False   False       False  False           False          False
7       False   True   False       False  False           False          False
8       False  False   False       False  False            True          False
9       False  False   False       False  False           False          False

In [19]:
df.isnull().sum()

Patient_ID        0
Age               2
Gender            1
Department        0
City              1
Treatment_Cost    2
Hospital_Stay     1
dtype: int64

DROPNA()  remove missing row

In [20]:
df.dropna()   # missing record hatane ke liye
# it check fo rna in hole data

   Patient_ID   Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0         101  25.0    Male  Cardiology  Nagpur         50000.0            5.0
1         102  45.0  Female   Neurology    Pune         35000.0            3.0
5         106  28.0  Female  Cardiology  Nagpur         55000.0            5.0
6         107  65.0    Male  Orthopedic  Mumbai         70000.0            7.0
9         110  30.0  Female  Orthopedic  Mumbai         50000.0            4.0

In [21]:
df.dropna(subset=["Age"])   # using subset it check only in single column for na

   Patient_ID   Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0         101  25.0    Male  Cardiology  Nagpur         50000.0            5.0
1         102  45.0  Female   Neurology    Pune         35000.0            3.0
3         104  60.0  Female  Orthopedic    None         45000.0            NaN
4         105  50.0    None   Neurology    Pune         30000.0            2.0
5         106  28.0  Female  Cardiology  Nagpur         55000.0            5.0
6         107  65.0    Male  Orthopedic  Mumbai         70000.0            7.0
8         109  55.0    Male  Cardiology  Nagpur             NaN            6.0
9         110  30.0  Female  Orthopedic  Mumbai         50000.0            4.0

FILL NA

In [22]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [23]:
df['Age']

0    25.00
1    45.00
2    44.75
3    60.00
4    50.00
5    28.00
6    65.00
7    44.75
8    55.00
9    30.00
Name: Age, dtype: float64