In [4]:
import pandas as pd

In [5]:
csv_movies = pd.read_csv(r"D:\ITP\DATA SCIENCE\data\imdb-top-1000.csv")

In [6]:
csv_movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

JOIN TWO DIFFERENT TABLES USING JOIN

In [7]:
movies = pd.DataFrame({
    "Genre": ["Drama", "Action", "Comedy"]
}, index=["Dangal", "Jawan", "3 Idiots"])

print(movies)

           Genre
Dangal     Drama
Jawan     Action
3 Idiots  Comedy

In [8]:
ratings = pd.DataFrame({
    "Rating": [8.4, 7.0, 8.4]
}, index=["Dangal", "Jawan", "3 Idiots"])

print(ratings)

          Rating
Dangal       8.4
Jawan        7.0
3 Idiots     8.4

In [9]:
#left join

In [10]:
print(movies.join(ratings,how='left'))

           Genre  Rating
Dangal     Drama     8.4
Jawan     Action     7.0
3 Idiots  Comedy     8.4

In [11]:
#right join
print(movies.join(ratings,how='right'))

           Genre  Rating
Dangal     Drama     8.4
Jawan     Action     7.0
3 Idiots  Comedy     8.4

In [12]:
# inner join
print(movies.join(ratings,how='inner'))

           Genre  Rating
Dangal     Drama     8.4
Jawan     Action     7.0
3 Idiots  Comedy     8.4

how = 
left - pahale table ke sare record
right - right table index
inner - sirf matching index
outer - dono table ke sabhi index

In [13]:
csv_movies.shape

(1000, 10)

In [14]:
csv_movies.columns

Index(['Series_Title', 'Released_Year', 'Runtime', 'Genre', 'IMDB_Rating',
       'Director', 'Star1', 'No_of_Votes', 'Gross', 'Metascore'],
      dtype='str')

In [15]:
# Table 1: Movie aur Genre
mov = csv_movies[["Series_Title", "Genre"]].copy()

# Table 2: Movie aur Rating
rat = csv_movies[["Series_Title", "IMDB_Rating"]].copy()

# Movie name ko index banayein
mov = mov.set_index("Series_Title")
rat = rat.set_index("Series_Title")

# Dono tables join karein
result = mov.join(rat)

print(result)

                           Genre  IMDB_Rating
Series_Title
The Shawshank Redemption   Drama          9.3
The Godfather              Crime          9.2
The Dark Knight           Action          9.0
The Godfather: Part II     Crime          9.0
12 Angry Men               Crime          9.0
...                          ...          ...
Breakfast at Tiffany's    Comedy          7.6
Giant                      Drama          7.6
From Here to Eternity      Drama          7.6
Lifeboat                   Drama          7.6
The 39 Steps               Crime          7.6

[1002 rows x 2 columns]

In [16]:
mov

                           Genre
Series_Title
The Shawshank Redemption   Drama
The Godfather              Crime
The Dark Knight           Action
The Godfather: Part II     Crime
12 Angry Men               Crime
...                          ...
Breakfast at Tiffany's    Comedy
Giant                      Drama
From Here to Eternity      Drama
Lifeboat                   Drama
The 39 Steps               Crime

[1000 rows x 1 columns]

In [17]:
rat

                          IMDB_Rating
Series_Title
The Shawshank Redemption          9.3
The Godfather                     9.2
The Dark Knight                   9.0
The Godfather: Part II            9.0
12 Angry Men                      9.0
...                               ...
Breakfast at Tiffany's            7.6
Giant                             7.6
From Here to Eternity             7.6
Lifeboat                          7.6
The 39 Steps                      7.6

[1000 rows x 1 columns]

In [18]:
# left join
result = mov.join(rat,how = 'left')
result

                           Genre  IMDB_Rating
Series_Title
The Shawshank Redemption   Drama          9.3
The Godfather              Crime          9.2
The Dark Knight           Action          9.0
The Godfather: Part II     Crime          9.0
12 Angry Men               Crime          9.0
...                          ...          ...
Breakfast at Tiffany's    Comedy          7.6
Giant                      Drama          7.6
From Here to Eternity      Drama          7.6
Lifeboat                   Drama          7.6
The 39 Steps               Crime          7.6

[1002 rows x 2 columns]

In [19]:
# right join 
res = mov.join(rat,how='right')
res

                           Genre  IMDB_Rating
Series_Title
The Shawshank Redemption   Drama          9.3
The Godfather              Crime          9.2
The Dark Knight           Action          9.0
The Godfather: Part II     Crime          9.0
12 Angry Men               Crime          9.0
...                          ...          ...
Breakfast at Tiffany's    Comedy          7.6
Giant                      Drama          7.6
From Here to Eternity      Drama          7.6
Lifeboat                   Drama          7.6
The 39 Steps               Crime          7.6

[1002 rows x 2 columns]

In [20]:
# inner join
r = mov.join(rat,how = "inner")
r

                           Genre  IMDB_Rating
Series_Title
The Shawshank Redemption   Drama          9.3
The Godfather              Crime          9.2
The Dark Knight           Action          9.0
The Godfather: Part II     Crime          9.0
12 Angry Men               Crime          9.0
...                          ...          ...
Breakfast at Tiffany's    Comedy          7.6
Giant                      Drama          7.6
From Here to Eternity      Drama          7.6
Lifeboat                   Drama          7.6
The 39 Steps               Crime          7.6

[1002 rows x 2 columns]

In [21]:
# outer join
r1 = mov.join(rat,how = "outer")
r1

                                 Genre  IMDB_Rating
Series_Title
(500) Days of Summer            Comedy          7.7
12 Angry Men                     Crime          9.0
12 Years a Slave             Biography          8.1
1917                             Drama          8.3
2001: A Space Odyssey        Adventure          8.3
...                                ...          ...
Zootopia                     Animation          8.0
Zulu                             Drama          7.7
Zwartboek                        Drama          7.7
À bout de souffle                Crime          7.8
Ôkami kodomo no Ame to Yuki  Animation          8.1

[1002 rows x 2 columns]

In [22]:
import pandas as pd

# Table 1: Movie details
movies = pd.DataFrame({
    "Genre": ["Drama", "Action", "Comedy", "Thriller"],
    "Year": [2016, 2023, 2009, 2022]
}, index=["Dangal", "Jawan", "3 Idiots", "Drishyam"])

# Table 2: Movie ratings
ratings = pd.DataFrame({
    "Rating": [8.4, 7.0, 8.4, 8.2],
    "Votes": [2000, 1500, 1800, 1200]
}, index=["Dangal", "Jawan", "PK", "Drishyam"])

print("MOVIES TABLE")
print(movies)

print("\nRATINGS TABLE")
print(ratings)

MOVIES TABLE
             Genre  Year
Dangal       Drama  2016
Jawan       Action  2023
3 Idiots    Comedy  2009
Drishyam  Thriller  2022

RATINGS TABLE
          Rating  Votes
Dangal       8.4   2000
Jawan        7.0   1500
PK           8.4   1800
Drishyam     8.2   1200

In [23]:
# left join
r2 = movies.join(ratings,how = "left")
r2

             Genre  Year  Rating   Votes
Dangal       Drama  2016     8.4  2000.0
Jawan       Action  2023     7.0  1500.0
3 Idiots    Comedy  2009     NaN     NaN
Drishyam  Thriller  2022     8.2  1200.0

In [24]:
# right join
r3 = movies.join(ratings,how = "right")
r3

             Genre    Year  Rating  Votes
Dangal       Drama  2016.0     8.4   2000
Jawan       Action  2023.0     7.0   1500
PK             NaN     NaN     8.4   1800
Drishyam  Thriller  2022.0     8.2   1200

In [25]:
# inner join
r4 = movies.join(ratings,how = "inner")
r4

             Genre  Year  Rating  Votes
Dangal       Drama  2016     8.4   2000
Jawan       Action  2023     7.0   1500
Drishyam  Thriller  2022     8.2   1200

In [26]:
# outer join
r5 = movies.join(ratings,how = "outer")
r5

             Genre    Year  Rating   Votes
3 Idiots    Comedy  2009.0     NaN     NaN
Dangal       Drama  2016.0     8.4  2000.0
Drishyam  Thriller  2022.0     8.2  1200.0
Jawan       Action  2023.0     7.0  1500.0
PK             NaN     NaN     8.4  1800.0