In [1]:
import pandas as pd

data = {
    "Patient_ID": [101,102,103,104,105,106,107,108,109,110],
    "Age": [25,45,35,60,50,28,65,40,55,30],
    "Gender": ["Male","Female","Male","Female","Male",
               "Female","Male","Female","Male","Female"],
    "Department": ["Cardiology","Neurology","Cardiology","Orthopedic",
                   "Neurology","Cardiology","Orthopedic","Neurology",
                   "Cardiology","Orthopedic"],
    "City": ["Nagpur","Pune","Nagpur","Mumbai","Pune",
             "Nagpur","Mumbai","Pune","Nagpur","Mumbai"],
    "Treatment_Cost": [50000,35000,60000,45000,30000,
                       55000,70000,40000,65000,50000],
    "Hospital_Stay": [5,3,6,4,2,5,7,3,6,4]
}

df = pd.DataFrame(data)

In [2]:
df

   Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0         101   25    Male  Cardiology  Nagpur           50000              5
1         102   45  Female   Neurology    Pune           35000              3
2         103   35    Male  Cardiology  Nagpur           60000              6
3         104   60  Female  Orthopedic  Mumbai           45000              4
4         105   50    Male   Neurology    Pune           30000              2
5         106   28  Female  Cardiology  Nagpur           55000              5
6         107   65    Male  Orthopedic  Mumbai           70000              7
7         108   40  Female   Neurology    Pune           40000              3
8         109   55    Male  Cardiology  Nagpur           65000              6
9         110   30  Female  Orthopedic  Mumbai           50000              4

In [5]:
# duplicate value banayi   puri row duplicate hui hai


# concat function is used for
df_duplicate = pd.concat([df,df.iloc[[2,5]]],ignore_index=True)
df_duplicate

    Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0          101   25    Male  Cardiology  Nagpur           50000              5
1          102   45  Female   Neurology    Pune           35000              3
2          103   35    Male  Cardiology  Nagpur           60000              6
3          104   60  Female  Orthopedic  Mumbai           45000              4
4          105   50    Male   Neurology    Pune           30000              2
5          106   28  Female  Cardiology  Nagpur           55000              5
6          107   65    Male  Orthopedic  Mumbai           70000              7
7          108   40  Female   Neurology    Pune           40000              3
8          109   55    Male  Cardiology  Nagpur           65000              6
9          110   30  Female  Orthopedic  Mumbai           50000              4
10         103   35    Male  Cardiology  Nagpur           60000              6
11         106   28  Female  Cardiology  Nagpur           55000              5

pd.concat() dataframes ko jodne ka kam karta hai


iloc[[2,5]] row 2 aur row select karna


ighnore_index = True index ko fresh numbereing dega

QUE : agar df 10 rows hain aur hum df.iloc[[2,5]] se 2 row aur add kar rahe hain to kitne rows hoge

ans : 12 rows

QUE : konsi row duplicate hogi

ans : 2,5   patient id 103,106

“Imagine karo hospital ke database mein Patient 103 ka same record do baar aa gaya. Ab hospital ke total patients count karenge to kya hoga?”

duplicated function


duplicate hai ya nahi

In [10]:
df_duplicate.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
dtype: bool

In [11]:
df_duplicate[df_duplicate.duplicated()]

    Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
10         103   35    Male  Cardiology  Nagpur           60000              6
11         106   28  Female  Cardiology  Nagpur           55000              5

In [16]:
df_clean = df_duplicate.drop_duplicates()

In [17]:
df_clean.shape

(10, 7)

duplicated ()  

duplicate identify karta hai


drop_duplicates()

duplicate remove karta hai

In [18]:
# agar patient 103 do ba

df_duplicate.duplicated(subset=["Patient_ID"])

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
dtype: bool

In [19]:
df_duplicate.drop_duplicates(subset=["Patient_ID"])

   Patient_ID  Age  Gender  Department    City  Treatment_Cost  Hospital_Stay
0         101   25    Male  Cardiology  Nagpur           50000              5
1         102   45  Female   Neurology    Pune           35000              3
2         103   35    Male  Cardiology  Nagpur           60000              6
3         104   60  Female  Orthopedic  Mumbai           45000              4
4         105   50    Male   Neurology    Pune           30000              2
5         106   28  Female  Cardiology  Nagpur           55000              5
6         107   65    Male  Orthopedic  Mumbai           70000              7
7         108   40  Female   Neurology    Pune           40000              3
8         109   55    Male  Cardiology  Nagpur           65000              6
9         110   30  Female  Orthopedic  Mumbai           50000              4