In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

3.0.6

In [3]:
data = {
    'name':['amit','riya','shivam','falguni','danish','mohini','harshit','naitik'],
    'age':[20,23,24,25,26,23,21,32],
    'city':['nagpur','chandrapur','gondia','gadchiroli','chandrapur','nagpur','warora','gondia'],
    'python_marks':[89,90,56,78,90,67,98,45],
    'sql_marks':[56,45,90,78,67,56,45,34],
    'Attendance':[90,90,78,86,84,93,95,92]
}

In [4]:
df = pd.DataFrame(data)

In [5]:
print(df)

      name  age        city  python_marks  sql_marks  Attendance
0     amit   20      nagpur            89         56          90
1     riya   23  chandrapur            90         45          90
2   shivam   24      gondia            56         90          78
3  falguni   25  gadchiroli            78         78          86
4   danish   26  chandrapur            90         67          84
5   mohini   23      nagpur            67         56          93
6  harshit   21      warora            98         45          95
7   naitik   32      gondia            45         34          92

BASIC INSPECTINS  DF.HEAD()  DF.TAIL()  PRINT(DF.SHAPE) PRINT(DF.COLUMNS)

In [6]:
df.head()

      name  age        city  python_marks  sql_marks  Attendance
0     amit   20      nagpur            89         56          90
1     riya   23  chandrapur            90         45          90
2   shivam   24      gondia            56         90          78
3  falguni   25  gadchiroli            78         78          86
4   danish   26  chandrapur            90         67          84

In [10]:
df.tail()

      name  age        city  python_marks  sql_marks  Attendance
3  falguni   25  gadchiroli            78         78          86
4   danish   26  chandrapur            90         67          84
5   mohini   23      nagpur            67         56          93
6  harshit   21      warora            98         45          95
7   naitik   32      gondia            45         34          92

In [11]:
print(df.shape)

(8, 6)

In [12]:
print(df.columns)

Index(['name', 'age', 'city', 'python_marks', 'sql_marks', 'Attendance'], dtype='str')

PRINTING ALL THE ROWS OF PARTICULAR COLUMN

In [13]:
print(df['name'])

0       amit
1       riya
2     shivam
3    falguni
4     danish
5     mohini
6    harshit
7     naitik
Name: name, dtype: str

FOR MULTIPLE COLUMN ACCESS   two square brackets used

In [14]:
print(df[['name','age','python_marks']])

      name  age  python_marks
0     amit   20            89
1     riya   23            90
2   shivam   24            56
3  falguni   25            78
4   danish   26            90
5   mohini   23            67
6  harshit   21            98
7   naitik   32            45

WE ARE SEARCHING FOR CITY == NAGPUR

In [15]:
print(df[df["city"]=="nagpur"])

     name  age    city  python_marks  sql_marks  Attendance
0    amit   20  nagpur            89         56          90
5  mohini   23  nagpur            67         56          93

python marks grater than 80

In [16]:
print(df[df["python_marks"]>80])

      name  age        city  python_marks  sql_marks  Attendance
0     amit   20      nagpur            89         56          90
1     riya   23  chandrapur            90         45          90
4   danish   26  chandrapur            90         67          84
6  harshit   21      warora            98         45          95

combining city = nagpur + pyhton marks > 80        # you can use |   symbol or & in all this case

In [17]:
print(df[(df["city"]=="nagpur") & (df["python_marks"]>80) ])

   name  age    city  python_marks  sql_marks  Attendance
0  amit   20  nagpur            89         56          90

ADVANCE FILTERS


sort values for data arrangements

In [18]:
df.sort_values("python_marks")

      name  age        city  python_marks  sql_marks  Attendance
7   naitik   32      gondia            45         34          92
2   shivam   24      gondia            56         90          78
5   mohini   23      nagpur            67         56          93
3  falguni   25  gadchiroli            78         78          86
0     amit   20      nagpur            89         56          90
1     riya   23  chandrapur            90         45          90
4   danish   26  chandrapur            90         67          84
6  harshit   21      warora            98         45          95

DAY 2 ASSIGNMENT

In [19]:
print(df["python_marks"].max())

98

In [20]:
print(df[df["python_marks"] == df["python_marks"].max()]["name"])

6    harshit
Name: name, dtype: str

In [21]:
print(df["sql_marks"].max())

90

In [22]:
print(df[df["sql_marks"] == df["sql_marks"].max()]["name"])

2    shivam
Name: name, dtype: str

In [23]:
print(df['python_marks'].min())

45

In [24]:
print(df[df['python_marks'] == df['python_marks'].min()]["name"])

7    naitik
Name: name, dtype: str

In [25]:
print(df['python_marks'].mean())

76.625

In [26]:
print(df['sql_marks'].mean())

58.875

In [27]:
print(df[df['python_marks']>80])

      name  age        city  python_marks  sql_marks  Attendance
0     amit   20      nagpur            89         56          90
1     riya   23  chandrapur            90         45          90
4   danish   26  chandrapur            90         67          84
6  harshit   21      warora            98         45          95

In [29]:
print(df[df["city"]=="nagpur"])

     name  age    city  python_marks  sql_marks  Attendance
0    amit   20  nagpur            89         56          90
5  mohini   23  nagpur            67         56          93

In [30]:
print(df[df['Attendance'] == df['Attendance'].max()])

      name  age    city  python_marks  sql_marks  Attendance
6  harshit   21  warora            98         45          95

In [31]:
print(df[df['Attendance'] == df['Attendance'].min()])

     name  age    city  python_marks  sql_marks  Attendance
2  shivam   24  gondia            56         90          78

In [32]:
print(df.sort_values("python_marks"))

      name  age        city  python_marks  sql_marks  Attendance
7   naitik   32      gondia            45         34          92
2   shivam   24      gondia            56         90          78
5   mohini   23      nagpur            67         56          93
3  falguni   25  gadchiroli            78         78          86
0     amit   20      nagpur            89         56          90
1     riya   23  chandrapur            90         45          90
4   danish   26  chandrapur            90         67          84
6  harshit   21      warora            98         45          95

In [33]:
print(df.sort_values("python_marks",ascending=False))

      name  age        city  python_marks  sql_marks  Attendance
6  harshit   21      warora            98         45          95
1     riya   23  chandrapur            90         45          90
4   danish   26  chandrapur            90         67          84
0     amit   20      nagpur            89         56          90
3  falguni   25  gadchiroli            78         78          86
5   mohini   23      nagpur            67         56          93
2   shivam   24      gondia            56         90          78
7   naitik   32      gondia            45         34          92

In [35]:
print(df[df["python_marks"]==67])

     name  age    city  python_marks  sql_marks  Attendance
5  mohini   23  nagpur            67         56          93

In [36]:
print(df[(df['python_marks']>80 & (df["Attendance"]>90))])

      name  age        city  python_marks  sql_marks  Attendance
0     amit   20      nagpur            89         56          90
1     riya   23  chandrapur            90         45          90
2   shivam   24      gondia            56         90          78
3  falguni   25  gadchiroli            78         78          86
4   danish   26  chandrapur            90         67          84
5   mohini   23      nagpur            67         56          93
6  harshit   21      warora            98         45          95
7   naitik   32      gondia            45         34          92

In [37]:
print(df[df['python_marks']<70])

     name  age    city  python_marks  sql_marks  Attendance
2  shivam   24  gondia            56         90          78
5  mohini   23  nagpur            67         56          93
7  naitik   32  gondia            45         34          92

In [40]:
print(df[(df['city'] == "nagpur") & (df['python_marks']>=60)])

     name  age    city  python_marks  sql_marks  Attendance
0    amit   20  nagpur            89         56          90
5  mohini   23  nagpur            67         56          93

In [41]:
print(df[df['Attendance']<85])

     name  age        city  python_marks  sql_marks  Attendance
2  shivam   24      gondia            56         90          78
4  danish   26  chandrapur            90         67          84

In [43]:
df[df['python_marks'] == df['python_marks'].max()][["name","city"]]

      name    city
6  harshit  warora

In [44]:
df[df['sql_marks']>=80][["name","sql_marks"]]

     name  sql_marks
2  shivam         90

In [45]:
df[(df['python_marks']<75) & (df['Attendance']<80)]

     name  age    city  python_marks  sql_marks  Attendance
2  shivam   24  gondia            56         90          78

In [47]:
df[(df["city"]=="nagpur") & (df['python_marks']>85)][["name","city","python_marks"]]

   name    city  python_marks
0  amit  nagpur            89

In [48]:
df.sort_values("python_marks",ascending=False).head(3)

      name  age        city  python_marks  sql_marks  Attendance
6  harshit   21      warora            98         45          95
1     riya   23  chandrapur            90         45          90
4   danish   26  chandrapur            90         67          84

In [49]:
df[(df['python_marks']>80) & (df['sql_marks']>80) & (df['Attendance']>85)]

Empty DataFrame
Columns: [name, age, city, python_marks, sql_marks, Attendance]
Index: []

In [50]:
df[(df['python_marks']<70) | (df['Attendance']<75)]

     name  age    city  python_marks  sql_marks  Attendance
2  shivam   24  gondia            56         90          78
5  mohini   23  nagpur            67         56          93
7  naitik   32  gondia            45         34          92

In [51]:
df[(df['python_marks']>80 & (df['Attendance']>85))]

      name  age        city  python_marks  sql_marks  Attendance
0     amit   20      nagpur            89         56          90
1     riya   23  chandrapur            90         45          90
2   shivam   24      gondia            56         90          78
3  falguni   25  gadchiroli            78         78          86
4   danish   26  chandrapur            90         67          84
5   mohini   23      nagpur            67         56          93
6  harshit   21      warora            98         45          95
7   naitik   32      gondia            45         34          92

In [52]:
df[(df['city']=="nagpur") & (df['python_marks']>80)]

   name  age    city  python_marks  sql_marks  Attendance
0  amit   20  nagpur            89         56          90

In [53]:
df[df['sql_marks']<75]

      name  age        city  python_marks  sql_marks  Attendance
0     amit   20      nagpur            89         56          90
1     riya   23  chandrapur            90         45          90
4   danish   26  chandrapur            90         67          84
5   mohini   23      nagpur            67         56          93
6  harshit   21      warora            98         45          95
7   naitik   32      gondia            45         34          92

In [54]:
df.sort_values("python_marks",ascending=False).head(3)

      name  age        city  python_marks  sql_marks  Attendance
6  harshit   21      warora            98         45          95
1     riya   23  chandrapur            90         45          90
4   danish   26  chandrapur            90         67          84

In [55]:
df[df['Attendance']<80][['name','city','Attendance']]

     name    city  Attendance
2  shivam  gondia          78

In [56]:
df[(df['python_marks']>=85) & (df['Attendance']>=90)]

      name  age        city  python_marks  sql_marks  Attendance
0     amit   20      nagpur            89         56          90
1     riya   23  chandrapur            90         45          90
6  harshit   21      warora            98         45          95

In [57]:
df[(df['python_marks']>80) & (df['sql_marks']>80) & (df['Attendance']>85)][['name','python_marks','sql_marks','Attendance']]

Empty DataFrame
Columns: [name, python_marks, sql_marks, Attendance]
Index: []