In [1]:
import pandas as pd

In [2]:
import pandas as pd

data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105",
                   "P106", "P107", "P108", "P109", "P110"],

    "Age": [45, 62, 34, 55, 41, 68, 29, 52, 47, 73],

    "City": ["Hyderabad", "Warangal", "Hyderabad", "Vijayawada",
             "Hyderabad", "Nizamabad", "Hyderabad", "Warangal",
             "Hyderabad", "Karimnagar"],

    "Surgery_Type": [
        "Cholecystectomy", "CABG", "Appendectomy",
        "Hernia Repair", "Knee Replacement", "PTCA",
        "Appendectomy", "Cholecystectomy",
        "Hernia Repair", "Knee Replacement"
    ],

    "Operation_Duration_Min": [90, 240, 75, 110, 180,
                               150, 70, 95, 120, 200],

    "Length_of_Stay_Days": [2, 7, 1, 3, 5,
                            4, 1, 2, 3, 6],

    "Admission_Type": [
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Planned"
    ]
}

df = pd.DataFrame(data)

In [3]:
df

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
3,P104,55,Vijayawada,Hernia Repair,110,3,Planned
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
5,P106,68,Nizamabad,PTCA,150,4,Emergency
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned

LOC FUNCTION


PANDAS NOTES — LOC

1️⃣ loc — Select Data Based on Labels or Conditions

Concept

loc is used to select rows and columns based on row/column labels or conditions.

 Basic Syntax:

df.loc[row, column]


2️⃣ Select a Specific Row

If we want the row with index 0:

df.loc[0]

This displays the complete row at index 0.


3️⃣ Select a Specific Row + Specific Column

To get the Patient_ID of the patient at index 0:

df.loc[0, "Patient_ID"]

Here:

0 → Row Index
"Patient_ID" → Column Name


4️⃣ Select Multiple Columns Using loc

To display Patient_ID and Surgery_Type for all patients:

df.loc[:, ["Patient_ID", "Surgery_Type"]]

Meaning of :

: = All Rows

So:

df.loc[:, ["Patient_ID", "Surgery_Type"]]

means:

All Rows + Selected Columns


5️⃣  loc with Condition

This is an important Data Analyst use-case.

To find patients from Hyderabad:

df.loc[df["City"] == "Hyderabad"]

Here:

df["City"] == "Hyderabad"

= Condition


6️⃣ Condition + Selected Columns

To find Hyderabad patients and display only selected information:

df.loc[
    df["City"] == "Hyderabad",
    ["Patient_ID", "Surgery_Type", "Admission_Type"]
]

 Important Pattern 

df.loc[condition, columns]

Remember this pattern:

df.loc[
    condition,
    selected columns
]

Example:

df.loc[
    df["City"] == "Hyderabad",
    ["Patient_ID", "Surgery_Type"]
]

 Meaning:

Find patients from Hyderabad and display only Patient_ID and Surgery_Type.


 KEY POINT

loc = Label / Condition-Based Selection

 Most Important Pattern:

df.loc[condition, columns]

In [4]:
df.loc[0]  # sccecific row  # index 0 vali row ayegi

Patient_ID                           P101
Age                                    45
City                            Hyderabad
Surgery_Type              Cholecystectomy
Operation_Duration_Min                 90
Length_of_Stay_Days                     2
Admission_Type                    Planned
Name: 0, dtype: object

In [5]:
df.loc[3]

Patient_ID                         P104
Age                                  55
City                         Vijayawada
Surgery_Type              Hernia Repair
Operation_Duration_Min              110
Length_of_Stay_Days                   3
Admission_Type                  Planned
Name: 3, dtype: object

In [6]:
df.loc[0,"Patient_ID"]

'P101'

In [7]:
df.loc[:,["Patient_ID","Surgery_Type"]]

  Patient_ID      Surgery_Type
0       P101   Cholecystectomy
1       P102              CABG
2       P103      Appendectomy
3       P104     Hernia Repair
4       P105  Knee Replacement
5       P106              PTCA
6       P107      Appendectomy
7       P108   Cholecystectomy
8       P109     Hernia Repair
9       P110  Knee Replacement

In [8]:
df.loc[df["City"]=="Hyderabad"]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned

df.loc[condition][columns]

In [9]:
df.loc[df["City"]=="Hyderabad"][["Patient_ID","Surgery_Type","Admission_Type"]]

  Patient_ID      Surgery_Type Admission_Type
0       P101   Cholecystectomy        Planned
2       P103      Appendectomy      Emergency
4       P105  Knee Replacement        Planned
6       P107      Appendectomy      Emergency
8       P109     Hernia Repair        Planned

In [10]:
df.loc[df["City"]=="Hyderabad",["Patient_ID","Surgery_Type","Admission_Type"]]

  Patient_ID      Surgery_Type Admission_Type
0       P101   Cholecystectomy        Planned
2       P103      Appendectomy      Emergency
4       P105  Knee Replacement        Planned
6       P107      Appendectomy      Emergency
8       P109     Hernia Repair        Planned

iloc --  position ke basis par selction

In [11]:
df.iloc[0]

Patient_ID                           P101
Age                                    45
City                            Hyderabad
Surgery_Type              Cholecystectomy
Operation_Duration_Min                 90
Length_of_Stay_Days                     2
Admission_Type                    Planned
Name: 0, dtype: object

In [12]:
df.iloc[1]

Patient_ID                     P102
Age                              62
City                       Warangal
Surgery_Type                   CABG
Operation_Duration_Min          240
Length_of_Stay_Days               7
Admission_Type            Emergency
Name: 1, dtype: object

In [13]:
df.iloc[0,0]   # row and column

'P101'

In [14]:
df.iloc[0:3]   # row from 0 1 2

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency

In [15]:
df.iloc[0:3,0:3]  # first three row and first three column

  Patient_ID  Age       City
0       P101   45  Hyderabad
1       P102   62   Warangal
2       P103   34  Hyderabad

In [16]:
df.iloc[0:5,0:5]   # first five row and first five column

  Patient_ID  Age        City      Surgery_Type  Operation_Duration_Min
0       P101   45   Hyderabad   Cholecystectomy                      90
1       P102   62    Warangal              CABG                     240
2       P103   34   Hyderabad      Appendectomy                      75
3       P104   55  Vijayawada     Hernia Repair                     110
4       P105   41   Hyderabad  Knee Replacement                     180

DIFFERENCE BETWEEN LOC AND ILOC

loc ---  label
iloc ---- position /index

df.loc[2,"City"]
df.iloc[2,2]

In [17]:
df.loc[2,"City"]

'Hyderabad'

In [18]:
df.iloc[2,2]

'Hyderabad'

In [19]:
# index 2 wale ki complete information

df.loc[2]

Patient_ID                        P103
Age                                 34
City                         Hyderabad
Surgery_Type              Appendectomy
Operation_Duration_Min              75
Length_of_Stay_Days                  1
Admission_Type               Emergency
Name: 2, dtype: object

In [20]:
# third patient ki complete information chahiye
df.iloc[2]

Patient_ID                        P103
Age                                 34
City                         Hyderabad
Surgery_Type              Appendectomy
Operation_Duration_Min              75
Length_of_Stay_Days                  1
Admission_Type               Emergency
Name: 2, dtype: object

1 . hospital wants to check the details of the forth patient

In [21]:
df.iloc[3]

Patient_ID                         P104
Age                                  55
City                         Vijayawada
Surgery_Type              Hernia Repair
Operation_Duration_Min              110
Length_of_Stay_Days                   3
Admission_Type                  Planned
Name: 3, dtype: object

2 . patient whose index label is 7

In [22]:
df.loc[7]

Patient_ID                           P108
Age                                    52
City                             Warangal
Surgery_Type              Cholecystectomy
Operation_Duration_Min                 95
Length_of_Stay_Days                     2
Admission_Type                    Planned
Name: 7, dtype: object

3 . display the first 5 patient , show only patient_id,city ,age

In [23]:
df.loc[0:5,["Patient_ID","City","Age"]]

  Patient_ID        City  Age
0       P101   Hyderabad   45
1       P102    Warangal   62
2       P103   Hyderabad   34
3       P104  Vijayawada   55
4       P105   Hyderabad   41
5       P106   Nizamabad   68

4 . last three patient data

In [24]:
df.tail(3)

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned

5 . patient_id and city

In [25]:
df[["Patient_ID","City"]]

  Patient_ID        City
0       P101   Hyderabad
1       P102    Warangal
2       P103   Hyderabad
3       P104  Vijayawada
4       P105   Hyderabad
5       P106   Nizamabad
6       P107   Hyderabad
7       P108    Warangal
8       P109   Hyderabad
9       P110  Karimnagar

6 . find all patients from warangal display -- patient id and surgery and age

In [26]:
df.loc[df["City"]=="Warangal"][["Patient_ID","Surgery_Type","Age"]]

  Patient_ID     Surgery_Type  Age
1       P102             CABG   62
7       P108  Cholecystectomy   52

7 . find patient whose age is greter than 50 print patientid age and city

In [27]:
df.loc[df["Age"]>50][["Patient_ID","City","Age"]]

  Patient_ID        City  Age
1       P102    Warangal   62
3       P104  Vijayawada   55
5       P106   Nizamabad   68
7       P108    Warangal   52
9       P110  Karimnagar   73

8 . row 2 to 5 and column 1 to 4

In [28]:
df.iloc[2:6,1:5]

   Age        City      Surgery_Type  Operation_Duration_Min
2   34   Hyderabad      Appendectomy                      75
3   55  Vijayawada     Hernia Repair                     110
4   41   Hyderabad  Knee Replacement                     180
5   68   Nizamabad              PTCA                     150

9 . patient at index 4 patient_ID surgerytype

In [29]:
df.loc[4,["Patient_ID","Surgery_Type"]]

Patient_ID                  P105
Surgery_Type    Knee Replacement
Name: 4, dtype: str

challenge find the youngest emergency patient print patientid age city

In [30]:
df.loc[(df["Admission_Type"]=="Emergency") & (df["Age"]==df["Age"].min())][["Patient_ID","City","Age"]]

  Patient_ID       City  Age
6       P107  Hyderabad   29