In [2]:
import pandas as pd

data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105",
                   "P106", "P107", "P108", "P109", "P110"],

    "Age": [45, 62, 34, 55, 41, 68, 29, 52, 47, 73],

    "City": ["Hyderabad", "Warangal", "Hyderabad", "Vijayawada",
             "Hyderabad", "Nizamabad", "Hyderabad", "Warangal",
             "Hyderabad", "Karimnagar"],

    "Surgery_Type": [
        "Cholecystectomy", "CABG", "Appendectomy",
        "Hernia Repair", "Knee Replacement", "PTCA",
        "Appendectomy", "Cholecystectomy",
        "Hernia Repair", "Knee Replacement"
    ],

    "Operation_Duration_Min": [90, 240, 75, 110, 180,
                               150, 70, 95, 120, 200],

    "Length_of_Stay_Days": [2, 7, 1, 3, 5,
                            4, 1, 2, 3, 6],

    "Admission_Type": [
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Planned"
    ]
}

df = pd.DataFrame(data)
print(df)

  Patient_ID  Age        City      Surgery_Type  Operation_Duration_Min  \
0       P101   45   Hyderabad   Cholecystectomy                      90
1       P102   62    Warangal              CABG                     240
2       P103   34   Hyderabad      Appendectomy                      75
3       P104   55  Vijayawada     Hernia Repair                     110
4       P105   41   Hyderabad  Knee Replacement                     180
5       P106   68   Nizamabad              PTCA                     150
6       P107   29   Hyderabad      Appendectomy                      70
7       P108   52    Warangal   Cholecystectomy                      95
8       P109   47   Hyderabad     Hernia Repair                     120
9       P110   73  Karimnagar  Knee Replacement                     200

   Length_of_Stay_Days Admission_Type
0                    2        Planned
1                    7      Emergency
2                    1      Emergency
3                    3        Planned
4                    5        Planned
5                    4      Emergency
6                    1      Emergency
7                    2        Planned
8                    3        Planned
9                    6        Planned

In [3]:
df.loc[0]

Patient_ID                           P101
Age                                    45
City                            Hyderabad
Surgery_Type              Cholecystectomy
Operation_Duration_Min                 90
Length_of_Stay_Days                     2
Admission_Type                    Planned
Name: 0, dtype: object

In [4]:
df.iloc[0]  # first row

Patient_ID                           P101
Age                                    45
City                            Hyderabad
Surgery_Type              Cholecystectomy
Operation_Duration_Min                 90
Length_of_Stay_Days                     2
Admission_Type                    Planned
Name: 0, dtype: object

In [5]:
df.iloc[1]  # second row

Patient_ID                     P102
Age                              62
City                       Warangal
Surgery_Type                   CABG
Operation_Duration_Min          240
Length_of_Stay_Days               7
Admission_Type            Emergency
Name: 1, dtype: object

In [6]:
df.iloc[0:3]  # first three rows

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency

df.iloc[row_position,column_position]

In [7]:
df.iloc[0,1]  # row and column selection

np.int64(45)

LOC VS ILOC

1) LOC
selection --- label/name and condition

2) ILOC
selction --- position/index

In [8]:
df.loc[0]

Patient_ID                           P101
Age                                    45
City                            Hyderabad
Surgery_Type              Cholecystectomy
Operation_Duration_Min                 90
Length_of_Stay_Days                     2
Admission_Type                    Planned
Name: 0, dtype: object

In [9]:
# p104 4 position par hai iloc kya likhege
df.loc[3]

Patient_ID                         P104
Age                                  55
City                         Vijayawada
Surgery_Type              Hernia Repair
Operation_Duration_Min              110
Length_of_Stay_Days                   3
Admission_Type                  Planned
Name: 3, dtype: object

In [10]:
import pandas as pd

data = {
    "Student": ["Amit", "Neha", "Rahul", "Pooja"],
    "Marks": [85, 92, 76, 88],
    "City": ["Nagpur", "Pune", "Mumbai", "Nashik"]
}

df = pd.DataFrame(data, index=[101, 105, 110, 115])

df

    Student  Marks    City
101    Amit     85  Nagpur
105    Neha     92    Pune
110   Rahul     76  Mumbai
115   Pooja     88  Nashik

In [11]:
df.loc[110]  # label 101

Student     Rahul
Marks          76
City       Mumbai
Name: 110, dtype: object

In [12]:
df.loc[101]

Student      Amit
Marks          85
City       Nagpur
Name: 101, dtype: object

In [13]:
df.iloc[0]

Student      Amit
Marks          85
City       Nagpur
Name: 101, dtype: object

In [14]:
df.iloc[0:2]

    Student  Marks    City
101    Amit     85  Nagpur
105    Neha     92    Pune

In [15]:
# position 1 to 3

df.iloc[1:3]

    Student  Marks    City
105    Neha     92    Pune
110   Rahul     76  Mumbai

iloc[start:stop] start included and stop excluded

In [16]:
df.iloc[0:3]

    Student  Marks    City
101    Amit     85  Nagpur
105    Neha     92    Pune
110   Rahul     76  Mumbai

In [17]:
# position 1 se 3 tak
df.iloc[1:4]

    Student  Marks    City
105    Neha     92    Pune
110   Rahul     76  Mumbai
115   Pooja     88  Nashik

ROW and Column slicing

In [18]:
df.loc[105,"Student"]

'Neha'

In [19]:
df.iloc[0:2,0:2]

    Student  Marks
101    Amit     85
105    Neha     92

In [20]:
df.tail(1)   # last row

    Student  Marks    City
115   Pooja     88  Nashik

In [21]:
df.iloc[2:4] # last two

    Student  Marks    City
110   Rahul     76  Mumbai
115   Pooja     88  Nashik

In [22]:
# first three row   df.iloc[:3]
df.iloc[0:3]

    Student  Marks    City
101    Amit     85  Nagpur
105    Neha     92    Pune
110   Rahul     76  Mumbai

In [23]:
# position se end tak
df.iloc[1:]

    Student  Marks    City
105    Neha     92    Pune
110   Rahul     76  Mumbai
115   Pooja     88  Nashik

In [24]:
# ek specific column ki first 3 values
df.iloc[0:3,1]  # 0:3 first three row  and 1 for column position (marks)

101    85
105    92
110    76
Name: Marks, dtype: int64

Std()  -- function (Standard deviation)

In [26]:
df['Marks'].std()

6.800735254367722